# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
   - garyschulte
   - jflo
   - fab-10
   - matkt
   - gezero
   - siladu
   - pinges
   - jframe

# role: ethpandaops.general.ethereum_node
ethereum_node_el: besu
# role: ethpandaops.general.besu
besu_container_name: execution
besu_container_image: "{{ default_ethereum_client_images.besu }}"
besu_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
besu_container_volumes:
  - "{{ besu_datadir }}:/data"
  - "{{ besu_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
besu_container_command_extra_args:
  - --genesis-file=/network-config/besu.json
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
  - --sync-mode=FULL
  - --data-storage-format=BONSAI
  - --bonsai-limit-trie-logs-enabled=false
  - --ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}:443
besu_container_pull: true
