# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
   - dapplion
   - wemeetagain
   - g11tech
   - philknows
   - nazarhussain
   - matthewkeil
   - twoeths
   - nflaig
   - ensi321
   - jeluard

# role: validator_keys
validator_keys_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/keys/"
    dest: "{{ lodestar_validator_datadir }}/keys/"
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/secrets/"
    dest: "{{ lodestar_validator_datadir }}/secrets/"

validator_bls_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/change_operations.json"
    dest: "{{ lodestar_validator_datadir }}/change_operations.json"
    owner: lodestar
    group: lodestar

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lodestar

# role: ethpandaops.general.lodestar
lodestar_container_name: beacon
lodestar_validator_container_name: validator
lodestar_container_image: "{{ default_ethereum_client_images.lodestar }}"
lodestar_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_cl_ports_http_beacon | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
lodestar_container_volumes:
  - "{{ lodestar_datadir }}:/data"
  - "{{ lodestar_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lodestar_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --genesisStateFile=/network-config/genesis.ssz
  - --bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --rest.namespace="*"
  - --network.connectToDiscv5Bootnodes
  - --nat=true
  - --chain.persistInvalidSszObjects=true
lodestar_validator_container_volumes:
  - "{{ lodestar_validator_datadir }}:/validator-data"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lodestar_validator_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --graffiti={{ ansible_hostname }}

lodestar_validator_datadir: /data/lodestar-validator
lodestar_container_pull: true
