name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@833d04dfd3c702c45fa5cbccffdf17a526d40ed2 # 833d04d

    - name: Install asdf tools
      shell: bash
      run: ./setup.sh