name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

    - name: Install asdf tools
      shell: bash
      run: ./setup.sh