# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethstats.yaml.j2

ethstats:
  fullnameOverride: ethstats

  image:
    repository: skylenet/ethstats-server
    tag: poa-no-geoip
    pullPolicy: IfNotPresent
  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: ethstats.pectra-devnet-3.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  secretEnv:
    WS_SECRET: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.ethstats_secret}>"

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
