localhost

[all:vars]
ethereum_network_name=pectra-msf-1

[bootnode]
bootnode-1 ansible_host=159.223.31.58 ipv6=2a03:b0c0:3:f0::ca2c:6000 cloud=digitalocean cloud_region=fra1

[grandine_besu]
grandine-besu-1 ansible_host=159.89.108.106 ipv6=2a03:b0c0:3:f0::ca2b:4000 cloud=digitalocean cloud_region=fra1 validator_start=29490 validator_end=29730

[grandine_erigon]
grandine-erigon-1 ansible_host=164.90.165.208 ipv6=2a03:b0c0:3:f0::ca2b:8000 cloud=digitalocean cloud_region=fra1 validator_start=29730 validator_end=30000

[grandine_geth]
grandine-geth-1 ansible_host=188.166.167.224 ipv6=2a03:b0c0:3:f0::ca2b:f000 cloud=digitalocean cloud_region=fra1 validator_start=27000 validator_end=28200

[grandine_nethermind]
grandine-nethermind-1 ansible_host=68.183.217.122 ipv6=2a03:b0c0:3:f0::ca2c:2000 cloud=digitalocean cloud_region=fra1 validator_start=28200 validator_end=29250

[grandine_reth]
grandine-reth-1 ansible_host=207.154.206.99 ipv6=2a03:b0c0:3:f0::ca2d:1000 cloud=digitalocean cloud_region=fra1 validator_start=29250 validator_end=29490

[lighthouse_besu]
lighthouse-besu-1 ansible_host=164.92.163.29 ipv6=2a03:b0c0:3:f0::ca2c:4000 cloud=digitalocean cloud_region=fra1 validator_start=13725 validator_end=14325

[lighthouse_erigon]
lighthouse-erigon-1 ansible_host=167.99.142.30 ipv6=2a03:b0c0:3:f0::ca2c:5000 cloud=digitalocean cloud_region=fra1 validator_start=14325 validator_end=15000

[lighthouse_geth]
lighthouse-geth-1 ansible_host=161.35.207.46 ipv6=2a03:b0c0:3:f0::ca2c:e000 cloud=digitalocean cloud_region=fra1 validator_start=7500 validator_end=10500

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=164.90.181.91 ipv6=2a03:b0c0:3:f0::ca2c:7000 cloud=digitalocean cloud_region=fra1 validator_start=10500 validator_end=13125

[lighthouse_reth]
lighthouse-reth-1 ansible_host=178.128.205.43 ipv6=2a03:b0c0:3:f0::ca2c:a000 cloud=digitalocean cloud_region=fra1 validator_start=13125 validator_end=13725

[lodestar_besu]
lodestar-besu-1 ansible_host=164.92.172.25 ipv6=2a03:b0c0:3:f0::ca2b:3000 cloud=digitalocean cloud_region=fra1 validator_start=23490 validator_end=23730

[lodestar_erigon]
lodestar-erigon-1 ansible_host=142.93.107.221 ipv6=2a03:b0c0:3:f0::ca2c:1000 cloud=digitalocean cloud_region=fra1 validator_start=23730 validator_end=24000

[lodestar_geth]
lodestar-geth-1 ansible_host=64.226.90.12 ipv6=2a03:b0c0:3:f0::ca2c:b000 cloud=digitalocean cloud_region=fra1 validator_start=21000 validator_end=22200

[lodestar_nethermind]
lodestar-nethermind-1 ansible_host=165.22.94.243 ipv6=2a03:b0c0:3:f0::ca2d:0 cloud=digitalocean cloud_region=fra1 validator_start=22200 validator_end=23250

[lodestar_reth]
lodestar-reth-1 ansible_host=68.183.72.178 ipv6=2a03:b0c0:3:f0::ca2c:0 cloud=digitalocean cloud_region=fra1 validator_start=23250 validator_end=23490

[nimbus_besu]
nimbus-besu-1 ansible_host=164.92.160.26 ipv6=2a03:b0c0:3:f0::ca2b:b000 cloud=digitalocean cloud_region=fra1 validator_start=26490 validator_end=26730

[nimbus_erigon]
nimbus-erigon-1 ansible_host=164.90.221.20 ipv6=2a03:b0c0:3:f0::ca2b:9000 cloud=digitalocean cloud_region=fra1 validator_start=26730 validator_end=27000

[nimbus_geth]
nimbus-geth-1 ansible_host=46.101.190.180 ipv6=2a03:b0c0:3:f0::ca2d:2000 cloud=digitalocean cloud_region=fra1 validator_start=24000 validator_end=25200

[nimbus_nethermind]
nimbus-nethermind-1 ansible_host=159.89.97.0 ipv6=2a03:b0c0:3:f0::ca2b:6000 cloud=digitalocean cloud_region=fra1 validator_start=25200 validator_end=26250

[nimbus_reth]
nimbus-reth-1 ansible_host=164.90.234.215 ipv6=2a03:b0c0:3:f0::ca2d:e000 cloud=digitalocean cloud_region=fra1 validator_start=26250 validator_end=26490

[prysm_besu]
prysm-besu-1 ansible_host=207.154.219.71 ipv6=2a03:b0c0:3:f0::ca2b:c000 cloud=digitalocean cloud_region=fra1 validator_start=6225 validator_end=6825

[prysm_erigon]
prysm-erigon-1 ansible_host=157.230.29.48 ipv6=2a03:b0c0:3:f0::ca2b:5000 cloud=digitalocean cloud_region=fra1 validator_start=6825 validator_end=7500

[prysm_geth]
prysm-geth-1 ansible_host=207.154.235.56 ipv6=2a03:b0c0:3:f0::ca2b:7000 cloud=digitalocean cloud_region=fra1 validator_start=0 validator_end=3000

[prysm_nethermind]
prysm-nethermind-1 ansible_host=64.226.115.3 ipv6=2a03:b0c0:3:f0::ca2d:d000 cloud=digitalocean cloud_region=fra1 validator_start=3000 validator_end=5625

[prysm_reth]
prysm-reth-1 ansible_host=64.226.72.206 ipv6=2a03:b0c0:3:f0::ca2c:d000 cloud=digitalocean cloud_region=fra1 validator_start=5625 validator_end=6225

[teku_besu]
teku-besu-1 ansible_host=157.230.18.160 ipv6=2a03:b0c0:3:f0::ca2b:e000 cloud=digitalocean cloud_region=fra1 validator_start=19980 validator_end=20460

[teku_erigon]
teku-erigon-1 ansible_host=64.227.126.103 ipv6=2a03:b0c0:3:f0::ca2c:3000 cloud=digitalocean cloud_region=fra1 validator_start=20460 validator_end=21000

[teku_geth]
teku-geth-1 ansible_host=164.90.236.18 ipv6=2a03:b0c0:3:f0::ca2b:a000 cloud=digitalocean cloud_region=fra1 validator_start=15000 validator_end=17400

[teku_nethermind]
teku-nethermind-1 ansible_host=165.22.73.134 ipv6=2a03:b0c0:3:f0::ca2d:3000 cloud=digitalocean cloud_region=fra1 validator_start=17400 validator_end=19500

[teku_reth]
teku-reth-1 ansible_host=164.92.240.21 ipv6=2a03:b0c0:3:f0::ca2c:f000 cloud=digitalocean cloud_region=fra1 validator_start=19500 validator_end=19980

[xatu]
xatu-1 ansible_host=164.92.254.102 ipv6=2a03:b0c0:3:f0::ca2f:0 cloud=digitalocean cloud_region=fra1


# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_erigon
lighthouse_geth
lighthouse_nethermind
lighthouse_reth
[lodestar:children]
lodestar_besu
lodestar_erigon
lodestar_geth
lodestar_nethermind
lodestar_reth
[nimbus:children]
nimbus_besu
nimbus_erigon
nimbus_geth
nimbus_nethermind
nimbus_reth
[teku:children]
teku_besu
teku_erigon
teku_geth
teku_nethermind
teku_reth
[prysm:children]
prysm_besu
prysm_erigon
prysm_geth
prysm_nethermind
prysm_reth
[grandine:children]
grandine_besu
grandine_erigon
grandine_geth
grandine_nethermind
grandine_reth

# Execution client groups

[besu:children]
grandine_besu
lighthouse_besu
lodestar_besu
nimbus_besu
prysm_besu
teku_besu
[ethereumjs:children]
[geth:children]
grandine_geth
lighthouse_geth
lodestar_geth
nimbus_geth
prysm_geth
teku_geth
[nethermind:children]
grandine_nethermind
lighthouse_nethermind
lodestar_nethermind
nimbus_nethermind
prysm_nethermind
teku_nethermind
[erigon:children]
grandine_erigon
lighthouse_erigon
lodestar_erigon
nimbus_erigon
prysm_erigon
teku_erigon
[erigonTwo:children]
[reth:children]
grandine_reth
lighthouse_reth
lodestar_reth
nimbus_reth
prysm_reth
teku_reth
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
besu
erigon
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node
#mevrelay

[tx_fuzz_blobs:children]
bootnode

[tx_fuzz_txs:children]
bootnode

[goomy:children]
bootnode

[mev_flood]
prysm-geth-1

[mev_boost:children]
mev_boost_bloxroute

[mev_boost_bloxroute]
prysm-geth-1
lighthouse-geth-1
nimbus-besu-1
lodestar-erigon-1
teku-reth-1

[mev_boost_ethpandaops]
#prysm-geth-2
#lighthouse-geth-2
#nimbus-geth-2
#lodestar-geth-2
#teku-geth-2
#prysm-nethermind-2
#lighthouse-nethermind-2
#nimbus-nethermind-2
#lodestar-nethermind-2
#teku-nethermind-2
#prysm-besu-2
#lighthouse-besu-2
#teku-besu-2
#grandine-geth-2
#grandine-nethermind-2
