
# enable slasher for lighthouse
lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --boot-nodes={{ ethereum_cl_bootnodes | join(',') }}
  - --invalid-gossip-verified-blocks-path=/data/lighthouse/invalid
  - --slasher
