# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/checkpointz.yaml.j2

checkpointz:
  fullnameOverride: checkpointz
  replicas: 1

  image:
    repository: ethpandaops/checkpointz
    tag: 0.0.5-electra-debian
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: checkpoint-sync.pectra-devnet-3.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

    tls:
    - hosts:
      - checkpoint-sync.pectra-devnet-3.ethpandaops.io
      secretName: pectra-devnet-3-checkpoint-sync-tls

  config:
    global:
      listenAddr: ":5555"
      logging: "info" # panic,fatal,warm,info,debug,trace
      metricsAddr: ":9090"

    checkpointz:
      mode: full
      caches:
        blocks:
          max_items: 100
        states:
          max_items: 5
      historical_epoch_count: 20

    beacon:
      upstreams:
      - name: rpc-teku-geth-001
        address: http://teku-geth-001:5052
        dataProvider: true
      - name: bootnode-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.bootnode-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true
      - name: grandine-besu-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-besu-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true
        dataProvider: true
      - name: lighthouse-besu-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-besu-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true
      - name: lodestar-nethermind-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-nethermind-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true

      - name: nimbus-reth-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-reth-1.pectra-devnet-3.ethpandaops.io
        dataProvider: true
      - name: prysm-geth-6
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-geth-6.pectra-devnet-3.ethpandaops.io
        dataProvider: true

      - name: teku-geth-5
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-geth-5.pectra-devnet-3.ethpandaops.io
        dataProvider: true