# role: ethpandaops.general.ethereum_node
ethereum_node_external_builder_enabled: true
ethereum_node_external_builder_type: mev_boost
ethereum_node_external_builder_container_name: external-block-builder
ethereum_node_external_builder_server_port: 18550
ethereum_node_external_builder_endpoint: "http://{{ ethereum_node_external_builder_container_name }}:{{ ethereum_node_external_builder_server_port }}"

# role: ethpandaops.general.mev_boost
mev_boost_container_image: ethpandaops/mev-boost:electra
mev_boost_container_command:
  - --addr=0.0.0.0:{{ mev_boost_server_port }}
  - --genesis-fork-version=0x10{{ ethereum_genesis_fork_version_suffix }}
  - --relay=http://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@54.147.158.197:18550 # bloxroute
