default_ethereum_client_images:
### Consensus layer clients
  lighthouse: docker.ethquokkaops.io/dh/sigp/lighthouse:v7.0.0-beta.0
  lodestar: docker.ethquokkaops.io/dh/chainsafe/lodestar:v1.27.0
  nimbus: docker.ethquokkaops.io/dh/statusim/nimbus-eth2:multiarch-v25.2.0
  prysm: docker.ethquokkaops.io/dh/prysmaticlabs/prysm-beacon-chain:v5.3.0
  prysm_validator: docker.ethquokkaops.io/dh/prysmaticlabs/prysm-validator:v5.3.0
  teku: docker.ethquokkaops.io/dh/consensys/teku:25.2.0
  grandine: docker.ethquokkaops.io/dh/sifrai/grandine:1.0.0
### Execution layer clients
  besu: docker.ethquokkaops.io/dh/hyperledger/besu:25.2.0
  geth: docker.ethquokkaops.io/dh/ethereum/client-go:v1.15.2
  erigon: docker.ethquokkaops.io/dh/erigontech/erigon:v2.61.1
  ethereumjs: docker.ethquokkaops.io/dh/ethpandaops/ethereumjs:eip7840
  nethermind: docker.ethquokkaops.io/dh/nethermind/nethermind:1.31.0
  reth: docker.ethquokkaops.io/gh/paradigmxyz/reth:v1.2.0
  reth_rbuilder: docker.ethquokkaops.io/dh/ethpandaops/rbuilder:reth-1.2.0
  nimbusel: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth1:devnet-6-pectra-82eeb34

default_tooling_images:
  mev_boost: docker.ethquokkaops.io/dh/ethpandaops/mev-boost:electra
  mev_boost_relay: docker.ethquokkaops.io/dh/ethpandaops/mev-boost-relay:electra-7fd62d4
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:1.0.25-debian
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:pr-56
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  ethstats: docker.ethquokkaops.io/dh/skylenet/ethstats-server:poa-no-geoip
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:0.0.12-electra
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:master-latest
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: docker.ethquokkaops.io/dh/ethpandaops/ethereum-genesis-generator:3.7.0
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:0.0.26-debian
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-a94b12blo
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:master-latest
  erpc: docker.ethquokkaops.io/gh/erpc/erpc:main
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  cl_bootnode: docker.ethquokkaops.io/dh/protolambda/eth2-bootnode:cleanup
  json_rpc_snooper: docker.ethquokkaops.io/dh/ethpandaops/json-rpc-snoop:1.1.0
  nginx_proxy: docker.ethquokkaops.io/dh/nginx:alpine
  nginx_proxy_gen: docker.ethquokkaops.io/dh/nginxproxy/docker-gen
  nginx_proxy_acme: docker.ethquokkaops.io/dh/nginxproxy/acme-companion
  vector: docker.ethquokkaops.io/dh/timberio/vector:0.30.0-alpine
  panda_pulse: docker.ethquokkaops.io/dh/ethpandaops/panda-pulse:0.0.10
