# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/Chart.yaml.j2

apiVersion: v2
name: blockscout
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: blockscout-stack
    repository: https://blockscout.github.io/helm-charts
    version: 2.0.0
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.x.x
