ansible_user: devops
ansible_python_interpreter: /usr/bin/python3
devnet_name: pectra

# IPv6 Specific configuration
global_ipv6_enabled: false
global_ipv6_subnet_ranges:
  hetzner: "64"
  digitalocean: "124"

######################################################
##
##          Role specific overwrites
##
######################################################

# role: ethpandaops.general.bootstrap
bootstrap_user: root
bootstrap_default_user_authorized_keys_github:
  # - barnabasbusa
  # - parithosh
  # - samcm
  # - savid
  # - skylenet

# role: robertdebock.fail2ban
fail2ban_loglevel: INFO
fail2ban_logtarget: /var/log/fail2ban.log
fail2ban_maxretry: 10
fail2ban_bantime: 600
fail2ban_ignoreips:
  - "127.0.0.1/8 ::1"
  - "{{ lookup('ansible.builtin.url', 'http://ifconfig.me/ip', split_lines=False) }}/32" # Avoid banning ourself


# role: ethpandaops.general.docker_network
docker_network_name: shared
docker_network_enable_ipv6: "{{ global_ipv6_enabled }}"
docker_network_ipam_config: >-
  {{ global_ipv6_enabled | ternary(
    [ { 'subnet': ansible_default_ipv6.address | ansible.utils.ipsubnet(global_ipv6_subnet_ranges[hostvars[inventory_hostname]['cloud']]) } ]
    , [])
  }}

docker_networks_shared:
  - name: "{{ docker_network_name }}"

# role: geerlingguy.docker
docker_users:
  - devops
docker_daemon_options:
  "log-driver": "json-file"
  "log-opts":
      "max-size": "250m"
      "max-file": "2"

# role: ethpandaops.general.prometheus
prometheus_container_networks: "{{ docker_networks_shared }}"

# role: ethpandaops.general.ethereum_node
ethereum_node_images_always_pull: true
