# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/assertoor.yaml.j2

assertoor:
  fullnameOverride: assertoor

  image:
    repository: ethpandaops/assertoor
    tag: electra-support-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor.pectra-devnet-2.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  ingressAdmin:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor-admin.pectra-devnet-2.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  endpoints:
    - name:  bootnode-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.bootnode-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.bootnode-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  grandine-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.grandine-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.grandine-reth-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  lighthouse-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lighthouse-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lighthouse-reth-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  lodestar-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.lodestar-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.lodestar-reth-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  nimbus-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.nimbus-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.nimbus-reth-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  prysm-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.prysm-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.prysm-reth-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-besu-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-besu-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-erigon-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-erigon-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-ethereumjs-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-ethereumjs-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-geth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-geth-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-nethermind-1.pectra-devnet-2.ethpandaops.io
    - name:  teku-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@rpc.teku-reth-1.pectra-devnet-2.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.node_ingress.combined}>@bn.teku-reth-1.pectra-devnet-2.ethpandaops.io

  validatorNamesInventory: https://config.pectra-devnet-2.ethpandaops.io/api/v1/nodes/validator-ranges
  globalVariables:
    walletPrivkey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.assertoor_private_key}>"
    clientPairNames:
      - bootnode-1
      - grandine-besu-1
      - grandine-erigon-1
      - grandine-ethereumjs-1
      - grandine-geth-1
      - grandine-nethermind-1
      - grandine-reth-1
      - lighthouse-besu-1
      - lighthouse-erigon-1
      - lighthouse-ethereumjs-1
      - lighthouse-geth-1
      - lighthouse-nethermind-1
      - lighthouse-reth-1
      - lodestar-besu-1
      - lodestar-erigon-1
      - lodestar-ethereumjs-1
      - lodestar-geth-1
      - lodestar-nethermind-1
      - lodestar-reth-1
      - nimbus-besu-1
      - nimbus-erigon-1
      - nimbus-ethereumjs-1
      - nimbus-geth-1
      - nimbus-nethermind-1
      - nimbus-reth-1
      - prysm-besu-1
      - prysm-erigon-1
      - prysm-ethereumjs-1
      - prysm-geth-1
      - prysm-nethermind-1
      - prysm-reth-1
      - teku-besu-1
      - teku-erigon-1
      - teku-ethereumjs-1
      - teku-geth-1
      - teku-nethermind-1
      - teku-reth-1
    validatorPairNames:
      - grandine-besu-1
      - grandine-erigon-1
      - grandine-ethereumjs-1
      - grandine-geth-1
      - grandine-nethermind-1
      - grandine-reth-1
      - lighthouse-besu-1
      - lighthouse-erigon-1
      - lighthouse-ethereumjs-1
      - lighthouse-nethermind-1
      - lighthouse-reth-1
      - lodestar-besu-1
      - lodestar-erigon-1
      - lodestar-ethereumjs-1
      - lodestar-geth-1
      - lodestar-nethermind-1
      - lodestar-reth-1
      - nimbus-besu-1
      - nimbus-erigon-1
      - nimbus-ethereumjs-1
      - nimbus-geth-1
      - nimbus-nethermind-1
      - nimbus-reth-1
      - prysm-besu-1
      - prysm-erigon-1
      - prysm-ethereumjs-1
      - prysm-geth-1
      - prysm-nethermind-1
      - prysm-reth-1
      - teku-besu-1
      - teku-erigon-1
      - teku-ethereumjs-1
      - teku-geth-1
      - teku-nethermind-1
      - teku-reth-1

  assertoorTests: []